name: Rust
on:
  push:
    branches: ["main"]
    paths:
      - '**/*.rs'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    paths:
      - '**/*.rs'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build
        run: nix develop . --command cargo build --verbose

      - name: Build release
        run: nix develop . --command cargo build --release --verbose

  check:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v5

      - name: Setup Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run cargo clippy
        run: nix develop . --command "cargo clippy -- -Dwarnings && cargo clippy --release -- -Dwarnings"

      - name: Run cargo fmt
        run: nix develop . --command cargo fmt --all --check
